# SPDX-License-Identifier: GPL-3.0-only
#
# Token is provided via GitHub secret CODECOV_TOKEN (or OIDC in workflow).

parsers:
  cobertura:
    partials_as_hits: true
    handle_missing_conditions: true

ignore:
  - "tests/**"

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto
