# SPDX-License-Identifier: GPL-3.0-only
name: Bug report
description: Report a defect in library behavior, packaging, or CI.
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is wrong and what did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Minimal steps, code, inputs, and exact command lines.
      placeholder: |
        1. Configure ...
        2. Run ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, compiler, compiler version, mode (asan/tsan/etc), and commit.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Output
      description: Paste failing logs and status codes.
